name: Call a reusable workflow

on:
  push:
    paths:
      - "caller2/**"
    branches:
      - master
jobs:
  call-general-workflow:
    uses: ./.github/workflows/called-generally.yml

  do-its-own-job:
    name: Run-Its-Own-Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run the service
        run: |
          node caller2/index2.js
          git diff --name-only $COMMIT_ID | awk -F'/' 'NF!=1{print $1}' | sort -u
