name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string


jobs:
  example_job:
    name: Echo Something
    runs-on: ubuntu-latest

    steps:
      # - uses: ./.github/workflows/my-action
      #   with:
      #     username: ${{ inputs.username }}
      
      - name: Print this
        run: echo $${{ inputs.username }}
