name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      directory:
        required: true
        type: string


jobs:
  example_job:
    name: Echo Something
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print this
        run: |
          echo ${{ inputs.username }}
          ls -la
          pwd
        
