name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      directory:
        required: true
        type: string


jobs:
  example_job:
    name: Echo Something
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ inputs.directory }}

      - name: Print this
        run: |
          echo ${{ inputs.username }}
          ls -la
          pwd
