name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      directory:
        required: true
        type: string


jobs:
  example_job:
    name: Echo Something
    runs-on: ubuntu-latest

    steps: 
      - name: Print this
        run: |
          echo ${{ inputs.username }}
          ls -la
          echo ${{ GITHUB_WORKSPACE }}
        # working-directory: ${{ inputs.directory }}
